name: Deploy Grill The Code To Int

# Workflow will be triggered as soon as a file is changed in the nginx-sample directory
on:
  workflow_dispatch:

jobs:
  Deploy_int:
    # Define the Github Actions Runner
    runs-on: [road-runner, Linux, X64, medium]
    if: github.ref == 'refs/heads/main'
    steps:
      # Checkout the repo on the Github Actions Runner
      - uses: actions/checkout@v4
      
      # Install "cf" CLI
      - name: Install CF CLI
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update && sudo apt-get upgrade
          sudo apt-get install --fix-missing
          sudo apt-get install -y apt-utils libgdiplus libc6-dev
          sudo apt-get install cf8-cli
          echo -n "Installed version of CF CLI (`which cf`): "
          cf -v
          
      - name: Install MXBuild
        run: |
          wget https://cdn.mendix.com/runtime/mxbuild-${{vars.mxversion}}.tar.gz
          tar -xvf mxbuild-${{vars.mxversion}}.tar.gz
          
      - name: Make mxbuild executable
        run: chmod +x ./modeler/mxbuild

      - name: Debug project file name
        run: echo "Project file -> ${{ vars.project_file_name }}"

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Mendix Application
        run: |
          ./modeler/mxbuild \
            --java-home=$JAVA_HOME \
            --java-exe-path=$JAVA_HOME/bin/java \
            ${{ vars.project_file_name }} \
            -o build.mda
      
      # Login to PC org
      - name: Login to our CF org
        run: |
          cf api ${{ secrets.cf_api_int }}
          cf auth ${{ secrets.cf_user_int }} ${{ secrets.cf_password_int }}
          cf target -o ${{ vars.org_name_int }}
      # Create new Space for github-actions
      - name: Target int Space
        run: |
          # check if target space exists ...
          if ! (cf space ${{ vars.space_name_int }} > /dev/null 2>&1)
          then
              exit 10
          else
            echo "Space \"${{ vars.space_name_int }}\" already exists"  
          fi
          # check if target to space is possible
          if ! (cf target -s ${{ vars.space_name_int }} > /dev/null 2>&1)
          then
            exit 20
          else
            cf target
          fi
      # Deploy the app to the ORG and space
      - name: Deploy app
        run: |
          cf target
          cf push ${{ vars.app_name_int }} -b https://github.com/mendix/cf-mendix-buildpack/releases/download/v${{ vars.buildpack_version_int }}/cf-mendix-buildpack.zip -p build.mda
      # Logout from cf after the deployment
      - name: Logout from CF
        run: cf logout
